# Generated by Django 4.2 on 2023-06-02 20:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=20, verbose_name='Name')),
                ('brand', models.CharField(max_length=10, verbose_name='Brand')),
                ('model', models.CharField(max_length=10, verbose_name='Model')),
                ('reg_number', models.CharField(max_length=10, verbose_name='Registration Number')),
                ('tech_insp', models.DateTimeField(verbose_name='Technical Inspection')),
            ],
        ),
    ]
