# Generated by Django 4.2 on 2023-06-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0002_alter_vehicle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=10, verbose_name='Brand')),
            ],
        ),
    ]
